# Generated by Django 4.2.2 on 2023-06-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_at', models.DateField(auto_now_add=True)),
                ('end_at', models.DateField()),
                ('status', models.CharField(choices=[('進行中', 'Doing'), ('中断', 'Pending'), ('完了', 'Done')], max_length=10)),
            ],
        ),
    ]
