# Generated by Django 4.2.2 on 2023-06-10 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateField(auto_now_add=True)),
                ('end_at', models.DateField()),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trackrecords')),
            ],
        ),
    ]
