# Generated by Django 4.2.2 on 2023-06-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pendingrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingrecords',
            name='end_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trackrecords',
            name='end_at',
            field=models.DateField(null=True),
        ),
    ]
