# Generated by Django 4.2.2 on 2023-06-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_pendingrecords_end_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingrecords',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingrecords',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trackrecords',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackrecords',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
